### ISSUE TITLE
Add a Change Password feature

### ISSUE THREAD

**Issue by Hexstream** [archimag/cliki2#12]
Apparently, it's only possible to change the email address (via http://cliki.net/site/preferences accessed by clicking on one's name after logging in) or "reset password", which generates a random password and sends it to the email address associated with the account.

It would be nice to be able to set a new password of one's own choosing ("enter old password, enter new password, confirm new password"). If there's already a way to do that, I didn't find it.

**Comment by Goheeca** [comment]
Exactly, this feature I'm missing, too.

**Comment by aarvid** [comment]
Me, too.  Someone reset my password and now I am stuck with a random password.

**Comment by vsedach** [comment]
This feature was added by Goheeca in https://github.com/vsedach/cliki2/pull/3

Should be deployed sometime in the next couple of months.

**Comment by Hexstream** [comment]
... Months for a deploy? That's some turnaround time... Anyway, thanks.

(Personal note: I've adopted password managers in the meantime, so this hasn't been a real issue for me for some time. But it's still nice that this is finally fixed.)
