### ISSUE TITLE
"transactions" to bundle related changes across many pages without "spamming" the changelog

### ISSUE THREAD

**Issue by Hexstream** [archimag/cliki2#15]
So, I know this one is a bit pie-in-the-sky and complex to do, but here goes:

When making one kind of change repeatedly across many pages, it would be nice to be able to "open a transaction" (a persistent set of related unapplied changes), then add many changesets to this transaction (possibly across days), and then at the end review all the changes and apply them all in one go. The user would be notified if conflicting changes were applied to some of the targetted pages in the meantime.

The changelog would report the apply of the "transaction" only, not each individual change, but of course it would be possible to click through to see all the changes applied by the transaction.

This would avoid "spamming" the changelog for big sets of related changes, help better plan such changes, help consistency by avoiding having some of the targetted pages updated while others not updated yet, and encourage consistency-improving "large-scale" changes by helping users in the aforementioned ways as well as preventing inhibition stemming from knowing the big set of changes would "spam" the changelog.

It would also be possible to "publish" in-progress transactions to advertise one's intentions in advance and sollicit public comments for improvements and such.

I hope this is all clear.

**Comment by vsedach** [comment]
TBH the best wiki is a bunch of text files (maybe Org mode) in a DVCS.
