### ISSUE TITLE
START-CLIKI-SERVER fails with reference to "index"

### ISSUE THREAD

**Issue by easye** [archimag/cliki2#17]
(in-package :cliki2)
(ensure-directories-exist "/var/tmp/cliki/lisp.not.org")
(start-cliki-server
  8081
  "/var/tmp/cliki"

   `("wiki.alu.org"
      ,(make-wiki "lisp.not.org" "Not Association of Lisp Users"
                 "/var/tmp/cliki/lisp.not.org" "noreply@lisp.not.org")))

**Comment by amherag** [comment]
Something that was happening to me was that if I used a domain name other than "localhost", it threw me an error of value NIL not being of type CLIKI2::WIKI or something like that. Maybe if you change "wiki.alu.org" to "localhost" your problem will get fixed.

If not, could you please elaborate more on the issue?

I hope this helps.

**Comment by vsedach** [comment]
If you look at the dispatcher for "/", the home page, it assumes that an article called "index" exists. You need to make the initial folder structure and the first article index by hand.

**Comment by vsedach** [comment]
Jianshi Huang fixed this in https://gitlab.common-lisp.net/vsedach/cliki2/commit/9a3e436f065f2e5f9c09696c37c456ef7f530073
