### ISSUE TITLE
sbcl-internals.cliki.net is down

### ISSUE THREAD

**Issue by izirku** [archimag/cliki2#19]
noticed this last night: sbcl-internals.cliki.net is down

**Comment by alex-eg** [comment]
It's down again (still?)

**Comment by vsedach** [comment]
The cliki.net box was moved to a different server, I forgot about the
sbcl-internals.cliki.net subdomain.

**Comment by vsedach** [comment]
Hi Vladimir,

Ok. I set up a subdomain for sbcl-internals for the cliki.net domain in the
zone file. Due to the move, that disappeared. The zone file points
sbcl-internals to the same host as that's handling the cliki.net domain. Is
that right?

Regards,

Erik.

On Wed, Oct 8, 2014 at 7:38 PM, Vladimir Sedach vsedach@gmail.com wrote:

> The cliki.net box was moved to a different server, I forgot about the
> sbcl-internals.cliki.net subdomain.
> 
> On Wed, Oct 8, 2014 at 3:03 AM, Alex Egorov notifications@github.com
> wrote:
> 
> > It's down again (still?)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/archimag/cliki2/issues/19#issuecomment-58335944.

## 

Bye,

Erik.

http://efficito.com -- Hosted accounting and ERP.
Robust and Flexible. No vendor lock-in.

**Comment by vsedach** [comment]
Yes, it's the same host.

**Comment by vsedach** [comment]
Ok. The Apache2 setup has been adjusted to reverse proxy
sbcl-internals.cliki.net as well.

Regards,

Eirk.

On Wed, Oct 8, 2014 at 8:29 PM, Vladimir Sedach vsedach@gmail.com wrote:

> Yes, it's the same host.
> 
> On Wed, Oct 8, 2014 at 11:08 AM, Erik Huelsmann ehuels@gmail.com wrote:
> 
> > Hi Vladimir,
> > 
> > Ok. I set up a subdomain for sbcl-internals for the cliki.net domain in
> > the zone file. Due to the move, that disappeared. The zone file points
> > sbcl-internals to the same host as that's handling the cliki.net domain.
> > Is that right?
> > 
> > Regards,
> > 
> > Erik.
> > 
> > On Wed, Oct 8, 2014 at 7:38 PM, Vladimir Sedach vsedach@gmail.com
> > wrote:
> > 
> > > The cliki.net box was moved to a different server, I forgot about the
> > > sbcl-internals.cliki.net subdomain.
> > > 
> > > On Wed, Oct 8, 2014 at 3:03 AM, Alex Egorov notifications@github.com
> > > wrote:
> > > 
> > > > It's down again (still?)
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/archimag/cliki2/issues/19#issuecomment-58335944.
> > 
> > ## 
> > 
> > Bye,
> > 
> > Erik.
> > 
> > http://efficito.com -- Hosted accounting and ERP.
> > Robust and Flexible. No vendor lock-in.

## 

Bye,

Erik.

http://efficito.com -- Hosted accounting and ERP.
Robust and Flexible. No vendor lock-in.

**Comment by alex-eg** [comment]
As for now it returns 500 Internal Server Error.

**Comment by vsedach** [comment]
Hi Erik,

Did the sbcl-internals directory get moved? http://sbcl-internals.cliki.net/
returns a 500.

Vladimir

**Comment by vsedach** [comment]
Hi Vladimir,

The sbcl-internals directory didn't get moved. When looking at my own
backups from the old server and at the directory /srv/cliki which holds the
wikis, the directory was never there... Meaning: it's not in my backups
from the old server...

Is that directory in your backups?

Regards,

Erik.

On Tue, Oct 21, 2014 at 8:01 PM, Vladimir Sedach vsedach@gmail.com wrote:

> Hi Erik,
> 
> Did the sbcl-internals directory get moved?
> http://sbcl-internals.cliki.net/ returns a 500.
> 
> Vladimir
> 
> On Wed, Oct 8, 2014 at 11:34 AM, Erik Huelsmann ehuels@gmail.com wrote:
> 
> > Ok. The Apache2 setup has been adjusted to reverse proxy
> > sbcl-internals.cliki.net as well.
> > 
> > Regards,
> > 
> > Eirk.
> > 
> > On Wed, Oct 8, 2014 at 8:29 PM, Vladimir Sedach vsedach@gmail.com
> > wrote:
> > 
> > > Yes, it's the same host.
> > > 
> > > On Wed, Oct 8, 2014 at 11:08 AM, Erik Huelsmann ehuels@gmail.com
> > > wrote:
> > > 
> > > > Hi Vladimir,
> > > > 
> > > > Ok. I set up a subdomain for sbcl-internals for the cliki.net domain
> > > > in the zone file. Due to the move, that disappeared. The zone file points
> > > > sbcl-internals to the same host as that's handling the cliki.net
> > > > domain. Is that right?
> > > > 
> > > > Regards,
> > > > 
> > > > Erik.
> > > > 
> > > > On Wed, Oct 8, 2014 at 7:38 PM, Vladimir Sedach vsedach@gmail.com
> > > > wrote:
> > > > 
> > > > > The cliki.net box was moved to a different server, I forgot about the
> > > > > sbcl-internals.cliki.net subdomain.
> > > > > 
> > > > > On Wed, Oct 8, 2014 at 3:03 AM, Alex Egorov notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > It's down again (still?)
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/archimag/cliki2/issues/19#issuecomment-58335944.
> > > > 
> > > > ## 
> > > > 
> > > > Bye,
> > > > 
> > > > Erik.
> > > > 
> > > > http://efficito.com -- Hosted accounting and ERP.
> > > > Robust and Flexible. No vendor lock-in.
> > 
> > ## 
> > 
> > Bye,
> > 
> > Erik.
> > 
> > http://efficito.com -- Hosted accounting and ERP.
> > Robust and Flexible. No vendor lock-in.

## 

Bye,

Erik.

http://efficito.com -- Hosted accounting and ERP.
Robust and Flexible. No vendor lock-in.

**Comment by karlosz** [comment]
Any update on this?

**Comment by vsedach** [comment]
Haven't taken a look yet, apologies.

**Comment by vsedach** [comment]
The person who administered SBCL Internals and the McCLIM clikis never provided the data. It should be possible to restore from Wayback Machine snapshots: https://web.archive.org/web/20120814000933/http://sbcl-internals.cliki.net/index
