### ISSUE TITLE
Cliki can not verify action in URL

### ISSUE THREAD

**Issue by alder** [archimag/cliki2#2]
If user want to add some page he press the link - http://cliki2.lisper.ru/edit/dfs1g. 'edit' is action. But we can change the link - http://cliki2.lisper.ru/add/dfs1g - and got error 404 by Hunchentoot. I think it would be better if Cliki will check the action property is incorrect.

**Comment by vsedach** [comment]
The URI structure has changed in the new version: https://github.com/vsedach/cliki2 Going to announce public beta 2 soon!
