### ISSUE TITLE
Troubles signing in...

### ISSUE THREAD

**Issue by marcoxa** [archimag/cliki2#21]
I try to sign in using my account name (marcoxa) and and says that the account does not exist.  Same if I try to reset the pw.

If I try to create an account with that name (marcoxa) cliki tells me that the account name is already taken.

Can you help?

Thanks

MA

**Comment by Hexstream** [comment]
Relatedly, I'm getting a 500 error when trying to reset my password. (This is different behavior than trying to reset the password of a non-existing account, which correctly says that that account doesn't exist.)

**Comment by vsedach** [comment]
cliki was moved to a new VPN server and this seems to have broken accounts
somehow. Investigating this issue.

**Comment by cmoore** [comment]
Has there been any progress on this?  Is there any way someone from the outside (like me) could help?

**Comment by vsedach** [comment]
I still haven't taken a look, sorry. If you'd like, email me at
vsedach@gmail.com and I can send you a backup snapshot of cliki data.

Vladimir

**Comment by vsedach** [comment]
Sign-in and password resets should be working.
