### ISSUE TITLE
How does one escape close parenthesis in an internal page name?

### ISSUE THREAD

**Issue by akater** [archimag/cliki2#24]
Given an internal page named “Lorem ipsum (dolor sit amet)”, how does one link to it with `_()` syntax? “Text formatting” page doesn't seem to provide an answer (I tried placing slashes in various ways to no avail), and “CLiki Style” page has no warnings suggesting to avoid such names.

**Comment by vsedach** [comment]
Added \) slash escaping in https://gitlab.common-lisp.net/vsedach/cliki2/commit/f356069e5b8505774fe16654414cedbb0b5a970f
