### ISSUE TITLE
Able to create page with no title, impossible to edit afterwards

### ISSUE THREAD

**Issue by defunkydrummer** [archimag/cliki2#25]
I mistakenly created a Wiki page without a title. The page now has no link afterwards, yet it is still in the wiki. 

See first line here:
https://www.cliki.net/Java

```
Packages that help with CL/Java integration:
- A simple example/wannabe-lib on how to use Swing UI components from Common Lisp (using ABCL)
```

I request, please, this wiki entry to be deleted, and a guard put in place to prevent further pages with no title being created.

**Comment by vsedach** [comment]
Known bug, I am planning to fix it in the next few months.

**Comment by defunkydrummer** [comment]
Thanks for the feedback! I added some pages to Cliki to keep it more up to date.

**Comment by vsedach** [comment]
Fixed in https://gitlab.common-lisp.net/vsedach/cliki2/commit/cad13e61b89700ce3b843a85d35068bc2043bc5f

Should be deployed to cliki.net in the next few weeks.
