### ISSUE TITLE
An error occured while processing your /site/view-revision request

### ISSUE THREAD

**Issue by alder** [archimag/cliki2#4]
Steps to reproduce:
1. Change id for view-revision URL. Example: http://74.207.228.11/site/view-revision?id=4+4546
2. Got Internal Server Error.

Details:
junk in string "4 4546"

P.S. Also this happens while processing /site/compare-revisions request. See - http://74.207.228.11/site/compare-revisions?old=4+4537&diff=44538

**Comment by vsedach** [comment]
This is the intended behavior.

**Comment by alder** [comment]
Much better behavior is 404 error. Not 500, not application code.

**Comment by andy128k** [comment]
Well designed 404 page have to be shown. Not 'server error'.

**Comment by vsedach** [comment]
There are 404 pages for articles and accounts. Revision IDs are permanent (except for "permanently deleted" pages ie spam) - if there is an error in viewing revisions or comparing them, then there is either an error in the URL or a serious server error. So 500 is the right behavior. All 500 pages return a stack trace to make error reporting easier.

**Comment by andy128k** [comment]
Ошибка валидации не должна приводить к 500 никогда.
Почитай что ли книжку. 4xx -- ошибка клиента. 5xx -- ошибка сервера.

P.S. С таким подходом толку от этого сайта не будет.

**Comment by alder** [comment]
Еще добавлю - на живом сайте пользователь никогда не должен видеть никаких стектрейсов. Это потенциальная уязвимость. Максимум - сообщение "Упс! Что-то пошло не так, мы уже в курсе и работаем над этим" и все ошибки логировать.

**Comment by vsedach** [comment]
Опять повторяю: это не ошибка валидации. Это или ошибка в базе данных, или ошибка в генерации URL. Если кто-то хочет найти уязвимость, то может спокойно прочитать код. А стек трейс упрощает дебаггинг для меня и пользователей cliki. Это же сайт для программистов.

**Comment by andy128k** [comment]
Пробел в url был добавлен пользователем. Он набрал url по-памяти (например).
http://cliki2-beta.cliki.net/site/view-revision?id=10000000
А это ошибка в базе или ещё где?
