### ISSUE TITLE
History view pops up (debug?) messages

### ISSUE THREAD

**Issue by epipping** [archimag/cliki2#7]
Go to http://74.207.228.11/site/history?title=zlib
or 
http://74.207.228.11/site/recent-changes

A message with the content "1" is printed when some entries are loaded. Those appear to be (a subset of)

Tue, 13 Dec 2011 08:51:19 GMT 178.137.21.73 ()
(prev)          Tue, 13 Dec 2011 08:49:59 GMT 178.137.21.73 ()
(prev)          Tue, 13 Dec 2011 08:49:18 GMT 178.137.21.73 ()
(prev)          Tue, 13 Dec 2011 08:36:03 GMT 178.137.21.73 ()
(prev)          Tue, 13 Dec 2011 08:27:51 GMT 178.137.21.73 ()

**Comment by alder** [comment]
See https://github.com/archimag/cliki2/issues/6. This is my testing changes.

**Comment by vsedach** [comment]
I've pushed a patch to fix this. Should be deployed shortly.
